<?php

/**
 * Posts API
 * Api to deal with posts and comments
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Posts API
 * @version 1.0.0
 */

/**
 * get index
 * Summary:
 * Notes: Get all posts.
 * Output-Formats: [application/json]
 */
Route::get('/api/v1/posts', 'Mohamed\PostsAPI\PostController@index');
/**
 * post store
 * Summary:
 * Notes: Create a new post.

 */
Route::post('/api/v1/posts', 'Mohamed\PostsAPI\PostController@store');
/**
 * delete destroy
 * Summary:
 * Notes: Delete post with id.

 */
Route::delete('/api/v1/posts/{post_id}', 'Mohamed\PostsAPI\PostController@destroy');
/**
 * get show
 * Summary:
 * Notes: Return post with id.
 * Output-Formats: [application/json]
 */
Route::get('/api/v1/posts/{post_id}', 'Mohamed\PostsAPI\PostController@show');
/**
 * put update
 * Summary:
 * Notes: Update post with id.

 */
Route::put('/api/v1/posts/{post_id}', 'Mohamed\PostsAPI\PostController@update');

